### DISCUSSION TITLE
Using TUnit in azure pipelines (test results and coverage)

### DISCUSSION THREAD

**Discussion by gentledepp** [thomhurst/TUnit#1264] [Q&A] [answered]
Hi!

I am trying to use TUnit in azure devops pipeline.

Using the out-of-the box VSTest tasks (1,2,3) does not work.
It does find the dll, but no "platform host" => so I install the `Microsoft.NET.Test.Sdk` nuget but then it does not find any tests - only the DLL
```yaml
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*Tests.dll
      **\*Test.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: False
    vsTestVersion: 'latest'
```

what _does_ work is running the tests using 
```yaml

  - task: PowerShell@2
    displayName: "dotnet test"
    inputs:
      targetType: 'inline'
      script: 'dotnet test $(solution) -c Debug -- --report-trx --coverage'

```

this runs the tests, but does not show the test results in the test results page.
This is a shame because _if_ a test fails I have no idea which one :-D
![image](https://github.com/user-attachments/assets/99be519a-827c-4c0a-890e-d4432cca8520)

Also, the code coverege page does not get any data either:
![image](https://github.com/user-attachments/assets/0e63cd20-b374-4901-b7cd-0824fcfb734d)

Has anyone got that to work already?

**Comment by thomhurst** [comment]
TUnit isn't built on top of VSTest as explained in the readme. Microsoft.NET.Test.Sdk should NOT be used with TUnit as it breaks it.

The second way using dotnet test would be the way to go for now.

As for not seeing results, you'll want to raise an issue with Microsoft and ask them to add support for Microsoft Testing Platform within Azure DevOps.

**Reply by gentledepp** [reply, marked as answer]
wow... so fast... 😅 
You _are_ awesome... nich was right :-D


In the meantime, I managed to get it to work!

Here is my default devops pipeline:

```yaml

# note: add a trigger that suits your needs
trigger:
  - develop 

# note: a windows machine is not required, but we use it anyways!
pool:
   vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'
  solution: 'MyAwesomeSolution.sln'
  buildPlatform: 'AnyCPU'
  
steps:
  - task: NuGetToolInstaller@1
  
  # simplest way to ensure everything you need is installed
  - task: PowerShell@2
    displayName: "dotnet workload restore"
    inputs:
      targetType: 'inline'
      script: 'dotnet workload restore src\$(solution)'

 # Note: We are used a private nuget feed in devops -> so we need to use the vstsfeed option - you may not need this!
  - task: NuGetCommand@2
    displayName: 'restore nuget packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*$(solution)'
      feedsToUse: 'select'
      vstsFeed: '<yourfeed>'
  
  # NOTE: This is where the magic happens. We specify an explicit results-directory for the subsequent tasks!
  - task: PowerShell@2
    displayName: "dotnet test"
    inputs:
      targetType: 'inline'
      script: 'dotnet test src\$(solution) -c Debug -- --report-trx --coverage  --results-directory $(Agent.TempDirectory)/TestResults'
 
  # this task publishes the test results
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '*.trx'
      mergeTestResults: true
      failTaskOnFailureToPublishResults: true
      failTaskOnMissingResultsFile: true
      searchFolder:  $(Agent.TempDirectory)/TestResults
  
  # and this the coverage results
  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: '$(Agent.TempDirectory)/TestResults/*.coverage'
      failIfCoverageEmpty: true
  

```

This works like a charm...
![image](https://github.com/user-attachments/assets/37b79b91-75d6-46cf-859f-d5f0b84869ba)


...except that the coverage report is "for pro users only"?
![image](https://github.com/user-attachments/assets/97552924-5810-49da-beb7-0caa799fe9a1)

What the heck 😅 
Can anybody let me know what kind of joke this is? :-D

aah... i see... the `PublishCodeCoverageResults` task uses the [ReportGenerator](https://github.com/sponsors/danielpalme) which requires a paid license... ugh...

**Reply by R-Vulcan** [reply]
The DotNetCoreCLI task with command 'test' automatically publishes test results, but to make it work with TUnit i had to set the results directory again after the `--`. 

The task does this by default but this gets ignored because its not set as an application argument (after `--`).

```yml
- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: test
    testRunTitle: 'Unit Tests'
    projects: 'tests/**/*Tests.csproj'
    arguments: '-c Release -- --coverage --report-trx --results-directory $(Agent.TempDirectory)'
```

Generated CLI command in pipeline:
```bash
/opt/hostedtoolcache/dotnet/dotnet test /home/vsts/work/1/s/.../SomeTests.csproj --logger trx --results-directory /home/vsts/work/_temp -c Release -- --coverage --report-trx --results-directory /home/vsts/work/_temp
```

Note how the --results-directory is set a second time after the `--`
