### ISSUE TITLE
[Help] "--report-trx" not found .NET 9

### ISSUE THREAD

**Issue by TimWoerner** [thomhurst/TUnit#2592]
using dotnet test in a project with TestingPlatformDotnetTestSupport enabled fails when specifying the "--report-trx" command

my setup:

```yml
- task: dotnetcorecli@2
  displayname: 'run tests'
  inputs:
    command: 'test'
    projects: |
      **/mention.test.infrastructure.tests.csproj
      **/mention.credentialprovider.test.csproj
      **/mention.user.test.csproj
      **/mention.wawi.test.csproj
    arguments: '--configuration $(buildconfiguration) --no-restore -m /nowarn:$(nowarnxmlcomments) -- --report-trx'
```

error:
```
"C:\Program Files\dotnet\dotnet.exe" test D:\work\1\s\src\tests\Mention.Test.Infrastructure.Tests\Mention.Test.Infrastructure.Tests.csproj --logger trx --results-directory D:\work\_temp --configuration Release --no-restore -m /nowarn:CS1570;CS1587;CS1711;CS1574;CS1584;CS1572;CS1658;CS1056 -- --report-trx
  ResXToStringLocalizerGenerator -> D:\work\1\s\src\libraries\Mention.I18n\generator\bin\Release\netstandard2.0\ResXToStringLocalizerGenerator.dll
  Mention.CredentialProvider.Abstractions -> D:\work\1\s\src\libraries\Mention.CredentialProvider.Abstractions\src\bin\Release\net9.0\Mention.CredentialProvider.Abstractions.dll
  Mention.Audit.Abstractions -> D:\work\1\s\src\libraries\Mention.Audit.Abstractions\src\bin\Release\net9.0\Mention.Audit.Abstractions.dll
  Mention.User.Abstractions -> D:\work\1\s\src\libraries\Mention.User.Abstractions\src\bin\Release\net9.0\Mention.User.Abstractions.dll
  Mention.Connect.Abstractions -> D:\work\1\s\src\libraries\Mention.Connect.Abstractions\src\bin\Release\net9.0\Mention.Connect.Abstractions.dll
  Mention.I18n -> D:\work\1\s\src\libraries\Mention.I18n\src\bin\Release\net9.0\Mention.I18n.dll
  Mention.Database -> D:\work\1\s\src\libraries\Mention.Database\src\bin\Release\net9.0\Mention.Database.dll
  Mention.Audit -> D:\work\1\s\src\libraries\Mention.Audit\src\bin\Release\net9.0\Mention.Audit.dll
  Mention.CredentialProvider -> D:\work\1\s\src\libraries\Mention.CredentialProvider\src\bin\Release\net9.0\Mention.CredentialProvider.dll
  Mention.CredentialProvider.AspNetCore -> D:\work\1\s\src\libraries\Mention.CredentialProvider.AspNetCore\src\bin\Release\net9.0\Mention.CredentialProvider.AspNetCore.dll
  Mention.User -> D:\work\1\s\src\libraries\Mention.User\src\bin\Release\net9.0\Mention.User.dll
  Mention.Test.Infrastructure -> D:\work\1\s\src\tests\Mention.Test.Infrastructure\bin\Release\net9.0\Mention.Test.Infrastructure.dll
  Mention.Test.Infrastructure.Tests -> D:\work\1\s\src\tests\Mention.Test.Infrastructure.Tests\bin\Release\net9.0\Mention.Test.Infrastructure.Tests.dll
  Run tests: 'D:\work\1\s\src\tests\Mention.Test.Infrastructure.Tests\bin\Release\net9.0\Mention.Test.Infrastructure.Tests.dll' [net9.0|x64]
  
  ████████╗██╗   ██╗███╗   ██╗██╗████████╗
  ╚══██╔══╝██║   ██║████╗  ██║██║╚══██╔══╝
     ██║   ██║   ██║██╔██╗ ██║██║   ██║
     ██║   ██║   ██║██║╚██╗██║██║   ██║
     ██║   ╚██████╔╝██║ ╚████║██║   ██║
     ╚═╝    ╚═════╝ ╚═╝  ╚═══╝╚═╝   ╚═╝
  
     TUnit v0.25.21.0 | 64-bit | Microsoft Windows 10.0.26100 | win-x64 | .NET 9.0.6 | Microsoft Testing Platform v1.7.3
  
     Engine Mode: SourceGenerated
  
  Unknown option '--report-trx'
```

I have the package `Microsoft.Testing.Platform.MSBuild` installed and in my .csproj for the test projects  I specified 
`<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>`

What am I doing wrong?
