### ISSUE TITLE
Zero tests ran when using SonarCloud with "sonar.dotnet.excludeTestProjects=true"

### ISSUE THREAD

**Issue by StefH** [thomhurst/TUnit#621]
When running TUnit tests in Azure DevOps on a Linux image, no tests are found?
```
Microsoft (R) Code Coverage Command Line Tool (x64)
Copyright (c) Microsoft Corporation. All rights reserved.

SessionId: efba60a0-d999-45b9-861b-f873f497f2a5
  Run tests: '/home/vsts/work/1/s/test/WireMock.Net.TUnitTests/bin/Debug/net8.0/WireMock.Net.TUnitTests.dll' [net8.0|x64]
  Failed! - Failed: 0, Passed: 0, Skipped: 0, Total: 0, Duration: 64ms
  
  Test run summary: Zero tests ran - /home/vsts/work/1/s/test/WireMock.Net.TUnitTests/bin/Debug/net8.0/WireMock.Net.TUnitTests.dll (net8.0|x64)
    total: 0
    failed: 0
    succeeded: 0
    skipped: 0
    duration: 123ms
/home/vsts/work/1/s/test/WireMock.Net.TUnitTests/bin/Debug/net8.0/WireMock.Net.TUnitTests.dll : error run failed: Tests failed: '/home/vsts/work/1/s/test/WireMock.Net.TUnitTests/bin/Debug/net8.0/TestResults/WireMock.Net.TUnitTests_net8.0_x64.log' [net8.0|x64] [/home/vsts/work/1/s/test/WireMock.Net.TUnitTests/WireMock.Net.TUnitTests.csproj]
Code coverage results: wiremock-coverage-tunit.xml.
```

Link to failed DevOps Build: (https://dev.azure.com/stef/WireMock.Net/_build/results?buildId=9212&view=logs&j=3bb91939-0fa9-522e-f055-9541addbc62d&t=dd3b8b64-cf8b-5723-be35-20e4eb86e2a7)

Command to run:
``` 
- task: CmdLine@2
    inputs:
      script: |
          dotnet-coverage collect "dotnet test ./test/WireMock.Net.TUnitTests/WireMock.Net.TUnitTests.csproj --configuration Debug --no-build --framework net8.0" -f xml -o "wiremock-coverage-tunit.xml"
    displayName: 'Execute WireMock.Net.Tests with Coverage'
```
